CREATE DATABASE IF NOT EXISTS comision_23546;

USE comision_23546;

CREATE TABLE usuarios
(ID INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT, 
Nombre VARCHAR(40) CHARACTER SET LATIN1 COLLATE latin1_swedish_ci NOT NULL,
Apellido VARCHAR(40) CHARACTER SET LATIN1 COLLATE latin1_swedish_ci NOT NULL, 
Edad TINYINT(2) NOT NULL, 
Fecha TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, 
Provincia VARCHAR(30) CHARACTER SET LATIN1 COLLATE latin1_swedish_ci NOT NULL);

DESCRIBE comision_23546.usuarios;


